### ISSUE TITLE
Last week of the season is not properly handled because there is no "next week" to check

### ISSUE THREAD

**Issue by andypymont** [andypymont/fantasypl#9]
Error initially on player view - but sense-check other areas too.

2015-05-13 11:54:18,771 :Exception on /players/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/andypymont/andypymontcouk/fantasypl/routes.py", line 328, in players
    player['waiver'] = waiver_status(player, gw_now['week'], gw_now['deadline'], gw_now['waiver'], next_gameweek()['waiver'])
  File "/home/andypymont/andypymontcouk/fantasypl/fantasypl.py", line 61, in next_gameweek
    rv = sorted(db.get('gameweeks', {'completed': False}), key=lambda gw: gw['week'])[1]
IndexError: list index out of range

**Comment by andypymont** [comment]
Also needed to add a dummy "Week zero" at the start of the season for similar reasons. Need to add functionality so that if the system can't get a week at either end of the scale, it generates a dummy object with sensible defaults?
